name: Bug Report
description: File a bug report
labels: [bug]
body:
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else we should know?
- type: input
  id: version
  attributes:
    label: Version of Jumpcat
